//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEcz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int id { get; set; }
        public string art { get; set; }
        public Nullable<int> kol { get; set; }
        public Nullable<System.DateTime> data_zak { get; set; }
        public Nullable<System.DateTime> dta_dost { get; set; }
        public Nullable<int> adres_punkta_dost { get; set; }
        public Nullable<int> id_zakzchika { get; set; }
        public Nullable<int> kod_polu { get; set; }
        public string stat { get; set; }
    
        public virtual PVZ PVZ { get; set; }
        public virtual Tovar Tovar { get; set; }
        public virtual User User { get; set; }
    }
}
